//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace svetotelegraf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("svetotelegraf.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signalling some text....
        /// </summary>
        public static string hidden_text {
            get {
                return ResourceManager.GetString("hidden_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop.
        /// </summary>
        public static string loop {
            get {
                return ResourceManager.GetString("loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In/output.
        /// </summary>
        public static string main_tab {
            get {
                return ResourceManager.GetString("main_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (on pause).
        /// </summary>
        public static string on_pause {
            get {
                return ResourceManager.GetString("on_pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pause.
        /// </summary>
        public static string pause_keyword {
            get {
                return ResourceManager.GetString("pause_keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only flashlight will be affected.
        /// </summary>
        public static string permissions_body {
            get {
                return ResourceManager.GetString("permissions_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please allow access to camera.
        /// </summary>
        public static string permissions_header {
            get {
                return ResourceManager.GetString("permissions_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play.
        /// </summary>
        public static string play_keyword {
            get {
                return ResourceManager.GetString("play_keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show your text in the notifications.
        /// </summary>
        public static string setting1 {
            get {
                return ResourceManager.GetString("setting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow sound signal during other media playback (not advised to turn off).
        /// </summary>
        public static string setting2 {
            get {
                return ResourceManager.GetString("setting2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock the sound state during signal.
        /// </summary>
        public static string setting3 {
            get {
                return ResourceManager.GetString("setting3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings_tab {
            get {
                return ResourceManager.GetString("settings_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string sound {
            get {
                return ResourceManager.GetString("sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no, you can&apos;t enable sound now.
        /// </summary>
        public static string sound_denied {
            get {
                return ResourceManager.GetString("sound_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speed: {0} symbols/min.
        /// </summary>
        public static string speed {
            get {
                return ResourceManager.GetString("speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop.
        /// </summary>
        public static string stop_keyword {
            get {
                return ResourceManager.GetString("stop_keyword", resourceCulture);
            }
        }
    }
}
